networks:
  server:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file:
      - .env
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - server
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - server

volumes:
  pgdata: